test3_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  Rev0_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev6
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rev1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev7
    pid: {p: 100.0, i: 0.01, d: 10.0}
  Rev3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev8
    pid: {p: 100.0, i: 0.01, d: 10.0}
